image:
  - Visual Studio 2022

environment:
  nodejs_version: '24'

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn

test_script:
  - node --version
  - choco install ffmpeg
  - node src/cli.js
  - SET ENVINFO_DEBUG=trace
  - npm run build
  - node dist/cli.js
  - SET ENVINFO_DEBUG=""
  - npm test

build: off
